serve - Add some preflight validation

diff --git a/tools/standalone/bin/serve b/tools/standalone/bin/serve
--- a/tools/standalone/bin/serve
+++ b/tools/standalone/bin/serve
@@ -2,12 +2,25 @@
 { # https://stackoverflow.com/a/21100710
   set -e
 
+  function fatal() {
+    echo >&2 "$@"
+    exit 1
+  }
+
   CORE="$PWD"
   SRV="$CORE/srv"
   ADDR_PORT="localhost:8000"
-  PHP_CLI_SERVER_WORKERS=5
+  export PHP_CLI_SERVER_WORKERS=5
 
-  export PHP_CLI_SERVER_WORKERS
+  if [ ! -d "$CORE/packages" ]; then
+    fatal "Missing: \"$CORE/packages\""
+  fi
+  if [ ! -e "$CORE/vendor/autoload.php" ]; then
+    fatal "Missing: \"$CORE/vendor/autoload.php\""
+  fi
+
+  php -r 'if (version_compare(PHP_VERSION, "8", "<")) echo "\n\n===========\nWARNING: In PHP 7.x, the built-in HTTP server may handle multiprocessing poorly!!\n===========\n";'
+  ## Specifically, the security-checks require auxiliary HTTP requests.
 
   echo "Update scaffolding ($SRV)"
   php "$CORE/tools/standalone/bin/scaffold" $SRV --auto
